#!/usr/bin/env python3
"""E2E rule-firing test for the Tracker Validation Tool (DHIS2 App Platform build).

Closes a coverage gap in review_suite.py: that suite drives the UI and verifies
that program rules / rule-variables / actions are correctly *created* via the
API, but never proves the generated rules actually *fire* (trigger their
SHOWERROR / SHOWWARNING) when tracker data is entered.

This standalone script proves rules fire at data-entry (import) time:

  1. Creates a self-contained program rule that mirrors what the app produces
     for a numeric field -- a SHOWERROR rule with condition
     `d2:hasValue(#{PRV}) && #{PRV} > <threshold>` plus its programRuleVariable
     (TEI_ATTRIBUTE) and programRuleAction -- on an existing tracker programme.
  2. Imports a tracked entity + enrollment via POST /api/tracker
     (importStrategy=CREATE, async=false), first with a value that VIOLATES the
     rule, then with a value that SATISFIES it.
  3. Asserts the DHIS2 tracker import report surfaces the program-rule effect
     for the violating payload and NOT for the valid one.

How program-rule SHOWERROR effects surface on /api/tracker import in 2.43
-------------------------------------------------------------------------
Verified empirically against DHIS2 2.43.0.1 (Laos HMIS demo). The tracker
importer runs the rule engine during import. A SHOWERROR whose condition is met
produces, in the synchronous import response:

    "status": "ERROR",
    "validationReport": {
        "errorReports": [{
            "message": "Generated by ProgramRule (`<ruleUid>`) - `<content>`.",
            "errorCode": "E1300",
            "trackerType": "ENROLLMENT",
            "uid": "<enrollmentUid>",
            "args": ["<ruleUid>", "<content>"]
        }],
        "warningReports": []
    }

and the import is BLOCKED -- stats show created:0 / ignored:N and the tracked
entity is NOT persisted (a subsequent GET returns 404). So the assertion for a
SHOWERROR rule is: import status == ERROR + an errorReport with code E1300 that
names the rule UID. (SHOWWARNING would instead appear under
validationReport.warningReports with the import still succeeding; this test
uses SHOWERROR to match the app's default action type.)

Usage:
    DHIS2_URL=http://dhis2-agent-laos-v43:8080 DHIS2_USER=local_admin \
    DHIS2_PASS=district python3 tests/e2e/rule_firing_test.py

Everything created (rule, action, PRV, and any tracked entities/enrollments) is
deleted at the end via the API regardless of pass/fail. Exit 0 = all passed.
"""
import base64
import json
import os
import sys
import traceback
import urllib.error
import urllib.request

BASE = os.environ.get("DHIS2_URL", "http://dhis2-agent-laos-v43:8080")
USER = os.environ.get("DHIS2_USER", "local_admin")
PASS = os.environ.get("DHIS2_PASS", "district")

# Unique marker so cleanup only ever touches what this script created.
MARKER = "[RFT-firing-test]"

# Target metadata (validated against the live 2.43 Laos instance).
PROGRAM_ID = "mD02n8fmxDF"          # HIV Prevention (OPEN access)
TET_ID = "MCPQUTHX1Ze"              # Person
ATTR_ID = "lAsTkcV1fvw"            # Age - Years (INTEGER_ZERO_OR_POSITIVE)
THRESHOLD = 120                     # rule fires when age > 120
VIOLATE_VALUE = "150"               # violates the rule (150 > 120)
VALID_VALUE = "30"                  # satisfies the rule (30 <= 120)

results = []       # (step, PASS/FAIL, note)
created_teis = []  # tracked-entity UIDs to clean up


def api(method, path, body=None):
    req = urllib.request.Request(
        f"{BASE}{path}",
        method=method,
        headers={
            "Authorization": "Basic "
            + base64.b64encode(f"{USER}:{PASS}".encode()).decode(),
            "Content-Type": "application/json",
        },
        data=json.dumps(body).encode() if body is not None else None,
    )
    try:
        with urllib.request.urlopen(req) as r:
            raw = r.read()
            return r.status, json.loads(raw) if raw else None
    except urllib.error.HTTPError as e:
        raw = e.read()
        try:
            return e.code, json.loads(raw)
        except Exception:
            return e.code, None


def record(step, ok, note=""):
    results.append((step, "PASS" if ok else "FAIL", note))
    print(f"{'PASS' if ok else 'FAIL'}: {step}" + (f" — {note}" if note else ""),
          flush=True)


def new_uids(n):
    _, data = api("GET", f"/api/system/id.json?limit={n}")
    return list((data or {}).get("codes", []))


def program_org_unit():
    """Resolve an org unit actually assigned to the target programme."""
    _, data = api("GET", f"/api/programs/{PROGRAM_ID}.json"
                         "?fields=organisationUnits[id]")
    ous = (data or {}).get("organisationUnits", [])
    if not ous:
        raise RuntimeError(f"programme {PROGRAM_ID} has no org units")
    return ous[0]["id"]


def import_tracker(ou, value):
    """Import a fresh TEI + enrollment carrying `value` for the rule attribute.

    Returns (import_report, tei_uid). Uses async=false so the report is the
    synchronous response body.
    """
    te, en = new_uids(2)
    created_teis.append(te)  # register for cleanup even if import is rejected
    payload = {
        "trackedEntities": [{
            "trackedEntity": te,
            "trackedEntityType": TET_ID,
            "orgUnit": ou,
            "enrollments": [{
                "enrollment": en,
                "program": PROGRAM_ID,
                "orgUnit": ou,
                "enrolledAt": "2024-01-01T00:00:00.000",
                "occurredAt": "2024-01-01T00:00:00.000",
                "status": "ACTIVE",
                "attributes": [{"attribute": ATTR_ID, "value": value}],
            }],
        }],
    }
    _, report = api("POST",
                    "/api/tracker?async=false&importStrategy=CREATE",
                    payload)
    return report or {}, te


def rule_effect_errors(report):
    """Return E1300 errorReports in the import report that name our rule."""
    vr = report.get("validationReport") or {}
    return [e for e in vr.get("errorReports", [])
            if e.get("errorCode") == "E1300"
            and RULE_ID in json.dumps(e.get("args", []))]


def setup_metadata():
    global PRV_ID, RULE_ID, ACTION_ID
    PRV_ID, RULE_ID, ACTION_ID = new_uids(3)

    code, resp = api("POST", "/api/programRuleVariables", {
        "id": PRV_ID,
        "name": "RFT_AGE_YEARS",
        "programRuleVariableSourceType": "TEI_ATTRIBUTE",
        "program": {"id": PROGRAM_ID},
        "trackedEntityAttribute": {"id": ATTR_ID},
    })
    if code >= 300:
        raise RuntimeError(f"PRV create failed: {code} {resp}")

    code, resp = api("POST", "/api/programRules", {
        "id": RULE_ID,
        "name": "RFT age too high",
        "description": f"{MARKER} rule-firing test",
        "program": {"id": PROGRAM_ID},
        "priority": 1,
        "condition": f"d2:hasValue(#{{RFT_AGE_YEARS}}) "
                     f"&& #{{RFT_AGE_YEARS}} > {THRESHOLD}",
    })
    if code >= 300:
        raise RuntimeError(f"rule create failed: {code} {resp}")

    code, resp = api("POST", "/api/programRuleActions", {
        "id": ACTION_ID,
        "programRule": {"id": RULE_ID},
        "programRuleActionType": "SHOWERROR",
        "content": f"RFT_ERROR age must be {THRESHOLD} or less",
    })
    if code >= 300:
        raise RuntimeError(f"action create failed: {code} {resp}")
    record("setup: PRV + SHOWERROR rule + action created", True,
           f"rule={RULE_ID}")


def main():
    ou = program_org_unit()
    setup_metadata()

    # ---- 1. violating payload -> rule must FIRE and BLOCK the import ----
    report, tei = import_tracker(ou, VIOLATE_VALUE)
    effects = rule_effect_errors(report)
    status = report.get("status")
    blocked = (report.get("stats") or {}).get("created", -1) == 0
    # confirm the violating TEI was not persisted
    persisted, _ = api("GET", f"/api/tracker/trackedEntities/{tei}")
    record("violating import fires SHOWERROR (E1300) and is blocked",
           status == "ERROR" and len(effects) == 1 and blocked
           and persisted == 404,
           f"status={status} effects={len(effects)} blocked={blocked} "
           f"persisted_http={persisted}")
    if effects:
        record("  effect message names the rule + content", True,
               effects[0].get("message", ""))

    # ---- 2. valid payload -> rule must NOT fire; import succeeds ----
    report, tei = import_tracker(ou, VALID_VALUE)
    effects = rule_effect_errors(report)
    status = report.get("status")
    created = (report.get("stats") or {}).get("created", 0)
    record("valid import does NOT fire the rule and succeeds",
           status == "OK" and len(effects) == 0 and created >= 1,
           f"status={status} effects={len(effects)} created={created}")


def cleanup():
    # tracker data first (enrollments cascade with the TEI)
    for te in created_teis:
        api("POST", "/api/tracker?async=false&importStrategy=DELETE",
            {"trackedEntities": [{"trackedEntity": te}]})
    # safety net: delete any TEI still carrying a firing/valid enrollment we made
    # (covered by created_teis above; no marker exists on tracker data).

    # metadata: discover by marker so a crashed run still cleans up.
    _, data = api("GET", f"/api/programRules.json?filter=program.id:eq:{PROGRAM_ID}"
                         "&fields=id,description&paging=false")
    deleted = {"actions": 0, "rules": 0, "prvs": 0}
    for r in (data or {}).get("programRules", []):
        if not (r.get("description") or "").startswith(MARKER):
            continue
        _, acts = api("GET", "/api/programRuleActions.json"
                             f"?filter=programRule.id:eq:{r['id']}"
                             "&fields=id&paging=false")
        for a in (acts or {}).get("programRuleActions", []):
            if api("DELETE", f"/api/programRuleActions/{a['id']}")[0] < 300:
                deleted["actions"] += 1
        if api("DELETE", f"/api/programRules/{r['id']}")[0] < 300:
            deleted["rules"] += 1
    _, prvs = api("GET", f"/api/programRuleVariables.json?filter=program.id:eq:{PROGRAM_ID}"
                         "&filter=name:eq:RFT_AGE_YEARS&fields=id&paging=false")
    for prv in (prvs or {}).get("programRuleVariables", []):
        if api("DELETE", f"/api/programRuleVariables/{prv['id']}")[0] < 300:
            deleted["prvs"] += 1
    print(f"cleanup: {deleted}, teis={len(created_teis)}", flush=True)


if __name__ == "__main__":
    failed = False
    try:
        main()
    except Exception:
        traceback.print_exc()
        failed = True
    finally:
        cleanup()

    print("\n=== rule-firing results ===")
    for step, status, note in results:
        print(f"{status}: {step}" + (f" — {note}" if note else ""))
    if failed or any(s == "FAIL" for _, s, _ in results) or not results:
        sys.exit(1)
    print("\nALL PASSED")
